version: "0.2"
language: en, es, pt-BR
files:
  - src/**/*.{tsx,ts,json}
ignorePaths:
  - src/data/dial-codes.ts
  - src/data/countries-dial-codes.json
dictionaryDefinitions:
  - name: spanish
    path: ./node_modules/@cspell/dict-es-es/Spanish.trie.gz
  - name: brazilian-portuguese
    path: ./node_modules/@cspell/dict-pt-br/pt_BR.trie.gz
dictionaries:
  - spanish
  - brazilian-portuguese
  - companies
  - softwareTerms
  - fonts
  - npm
words:
  - awsapps
  - bakertilly
  - Bellet
  - camelcase
  - çñüöëïä
  - corfo
  - devcert
  - endregion
  - fontawesome
  - formik
  - fortawesome
  - harelpls
  - isplainobject
  - kebabcase
  - msapplication
  - nocheck
  - Offcanvas
  - pascalcase
  - pucv
  - recaptcha
  - rehype
  - Requireable
  - stratego
  - sumn
  - uncapitalize
  - uniqid
  - unmarshall
  - whitesmoke
  - Winkler
  - Xmark
