---
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  install-node:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '18.16'
      - run: node --version

  install-pnpm:
    executor: node/default
    steps:
      - checkout
      - run:
          name: "Install PNPM globally"
          command: npm install -g pnpm

  lint:
    executor: node/default
    description: "Run tests"
    steps:
      - checkout
      - run:
          name: "Install local dependencies"
          command: pnpm install
      - run:
          name: "Check linting"
          command: pnpm lint

workflows:
  test:
    jobs:
      - install-node
      - install-pnpm
      - lint
